[[redirects]]
  from = "/api/push/send"
  to = "/.netlify/functions/push-send"
  status = 200
[[redirects]]
  from = "/api/push/subscribe"
  to = "/.netlify/functions/push-subscribe"
  status = 200

[[redirects]]
  from = "/api/push/unsubscribe"
  to = "/.netlify/functions/push-unsubscribe"
  status = 200
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/screenshots/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
